version: '2'
services:
  web:
    build: ./
    ports:
      - "80:80"
    #command: celery multi start -A main.celery_app worker --loglevel=info
  redis_db:
    image: redis:3.2-alpine
    volumes:
      - redis_data:/data
volumes:  
  redis_data: